import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("flocks", "0001_initial"), ("inventory", "0001_initial")]
    operations = [
        migrations.CreateModel(name="Vaccination", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("scheduled_date", models.DateField(db_index=True)), ("administered_date", models.DateField(blank=True, null=True)), ("dose_quantity", models.DecimalField(decimal_places=2, default=0, max_digits=12)), ("status", models.CharField(choices=[("scheduled", "Scheduled"), ("completed", "Completed"), ("missed", "Missed")], db_index=True, default="scheduled", max_length=20)), ("notes", models.TextField(blank=True)), ("batch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="vaccinations", to="flocks.flockbatch")), ("vaccine", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="vaccinations", to="inventory.inventoryitem")), ("stock_transaction", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="vaccination", to="inventory.stocktransaction")), ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="health_vaccination_created", to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="MedicationRecord", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("start_date", models.DateField(db_index=True)), ("end_date", models.DateField(blank=True, null=True)), ("dosage", models.CharField(max_length=100)), ("reason", models.TextField()), ("quantity_used", models.DecimalField(decimal_places=2, default=0, max_digits=12)), ("batch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="medications", to="flocks.flockbatch")), ("medicine", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="medications", to="inventory.inventoryitem")), ("stock_transaction", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="medication_record", to="inventory.stocktransaction")), ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="health_medicationrecord_created", to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="DiseaseRecord", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("disease_name", models.CharField(max_length=150)), ("diagnosed_date", models.DateField(db_index=True)), ("affected_birds", models.PositiveIntegerField(default=0)), ("symptoms", models.TextField(blank=True)), ("treatment", models.TextField(blank=True)), ("resolved_date", models.DateField(blank=True, null=True)), ("batch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="disease_records", to="flocks.flockbatch")), ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="health_diseaserecord_created", to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="VetVisit", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("visit_date", models.DateField(db_index=True)), ("veterinarian", models.CharField(max_length=150)), ("reason", models.TextField()), ("findings", models.TextField(blank=True)), ("recommendations", models.TextField(blank=True)), ("follow_up_date", models.DateField(blank=True, db_index=True, null=True)), ("batch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="vet_visits", to="flocks.flockbatch")), ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="health_vetvisit_created", to=settings.AUTH_USER_MODEL))]),
    ]
