import ResourcePage from "../components/tables/ResourcePage";
import ResourceTabs from "../components/layout/ResourceTabs";
import { toast } from "sonner";
import { api, apiError } from "../lib/api";

const c = (key, label, format) => ({ key, label, format });
const f = (name, label, type = "text", extra = {}) => ({ name, label, type, ...extra });
const choice = (name, label, options, required = true) => f(name, label, "select", { options, required });
const remote = (name, label, optionsEndpoint, optionLabel, required = true) => f(name, label, "remote", { optionsEndpoint, optionLabel, required });
const date = (name, label, required = true) => f(name, label, "date", { required });
const number = (name, label, required = true, step = "1") => f(name, label, "number", { required, min: 0, step });

const birdTypes = [["layers", "Layers"], ["broilers", "Broilers"], ["kienyeji", "Kienyeji"], ["breeders", "Breeders"]];
const batchStatuses = [["planned", "Planned"], ["active", "Active"], ["quarantined", "Quarantined"], ["closed", "Closed"]];
const paymentMethods = [["cash", "Cash"], ["mobile_money", "Mobile money"], ["bank", "Bank transfer"], ["credit", "Credit"]];

function PrintInvoice({ sale }) {
  async function open() {
    try {
      const { data } = await api.get(`/sales/${sale.id}/invoice/`, { responseType: "blob" });
      const url = URL.createObjectURL(new Blob([data], { type: "text/html" }));
      window.open(url, "_blank", "noopener,noreferrer");
      setTimeout(() => URL.revokeObjectURL(url), 60000);
    } catch (error) { toast.error(apiError(error)); }
  }
  return <button type="button" onClick={open} className="font-semibold text-farm-700 underline">{sale.invoice_number}</button>;
}

function PaymentButton({ sale, reload }) {
  async function update() {
    const entered = window.prompt(`Total: ${sale.total_amount}. Enter cumulative amount paid:`, sale.amount_paid);
    if (entered === null) return;
    try {
      await api.post(`/sales/${sale.id}/payment/`, { amount_paid: entered, payment_method: sale.payment_method });
      toast.success("Payment updated."); reload();
    } catch (error) { toast.error(apiError(error)); }
  }
  return <button type="button" onClick={update} className="btn-secondary min-h-9 px-3 text-xs">Update payment</button>;
}

export function HousesPage(props) { return <ResourcePage {...props} title="Poultry houses" description="Capacity, occupancy, and cleaning schedules." endpoint="/farm/houses/"
  columns={[c("name", "House"), c("current_occupancy", "Occupancy"), c("capacity", "Capacity"), c("next_cleaning_at", "Next cleaning"), c("is_active", "Active")]}
  fields={[f("name", "House name", "text", { required: true }), number("capacity", "Capacity"), number("cleaning_interval_days", "Cleaning interval (days)"), date("last_cleaned_at", "Last cleaned", false), date("next_cleaning_at", "Next cleaning", false), choice("is_active", "Status", [[true, "Active"], [false, "Inactive"]]), f("notes", "Notes", "textarea", { full: true })]} />; }

function Batches(props) { return <ResourcePage {...props} title="Batches" endpoint="/flocks/batches/" allowDelete={false}
  columns={[c("batch_code", "Code"), c("batch_name", "Batch"), c("bird_type", "Type"), c("breed_name", "Breed"), c("current_bird_count", "Birds"), c("poultry_house_name", "House"), c("status", "Status")]}
  fields={[f("batch_code", "Batch code", "text", { required: true }), f("batch_name", "Batch name", "text", { required: true }), choice("bird_type", "Bird type", birdTypes), remote("breed", "Breed", "/flocks/breeds/"), remote("supplier", "Supplier", "/flocks/suppliers/", null, false), date("arrival_date", "Arrival date"), number("initial_bird_count", "Initial birds"), number("purchase_cost", "Purchase cost", true, "0.01"), remote("poultry_house", "Poultry house", "/farm/houses/"), choice("status", "Status", batchStatuses), f("notes", "Notes", "textarea", { full: true })]} />; }
function Breeds(props) { return <ResourcePage {...props} title="Breeds" endpoint="/flocks/breeds/" columns={[c("name", "Breed"), c("description", "Description"), c("is_active", "Active")]} fields={[f("name", "Breed name", "text", { required: true }), f("description", "Description", "textarea", { full: true }), choice("is_active", "Status", [[true, "Active"], [false, "Inactive"]])]} />; }
function BirdSuppliers(props) { return <ResourcePage {...props} title="Bird suppliers" endpoint="/flocks/suppliers/" columns={[c("name", "Supplier"), c("contact_person", "Contact"), c("phone_number", "Phone"), c("is_active", "Active")]} fields={[f("name", "Supplier", "text", { required: true }), f("contact_person", "Contact person"), f("phone_number", "Phone"), f("email", "Email", "email"), f("notes", "Notes", "textarea", { full: true })]} />; }
function BirdMovements(props) { return <ResourcePage {...props} title="Bird movements" endpoint="/flocks/movements/" createOnly columns={[c("movement_date", "Date"), c("batch_code", "Batch"), c("movement_type", "Type"), c("quantity", "Quantity"), c("reference", "Reference")]} fields={[remote("batch", "Batch", "/flocks/batches/", (x) => `${x.batch_code} — ${x.batch_name}`), choice("movement_type", "Movement", [["mortality", "Mortality"], ["sale", "Sale"], ["adjustment_in", "Adjustment in"], ["adjustment_out", "Adjustment out"]]), number("quantity", "Quantity"), date("movement_date", "Date"), f("reference", "Reference"), f("notes", "Notes", "textarea", { full: true })]} />; }
export function FlocksPage() { return <ResourceTabs title="Flocks" description="Batches, breeds, suppliers, and bird movements." tabs={[{ label: "Batches", component: Batches }, { label: "Movements", component: BirdMovements }, { label: "Breeds", component: Breeds }, { label: "Suppliers", component: BirdSuppliers }]} />; }

export function DailyRecordsPage(props) { return <ResourcePage {...props} workerCreate title="Daily records" description="Fast daily entry for workers in the poultry houses." endpoint="/daily-records/"
  columns={[c("record_date", "Date"), c("batch_code", "Batch"), c("eggs_collected", "Eggs"), c("feed_issued_kg", "Feed kg"), c("sick_birds", "Sick"), c("dead_birds", "Mortality"), c("recorded_by", "Recorded by")]}
  fields={[remote("batch", "Batch", "/flocks/batches/", (x) => `${x.batch_code} — ${x.batch_name}`), date("record_date", "Record date"), number("eggs_collected", "Eggs collected"), number("broken_eggs", "Broken eggs"), number("dirty_eggs", "Dirty eggs"), remote("feed_item", "Feed item", "/inventory/items/", (x) => `${x.name} — ${x.current_stock} ${x.unit}`, false), number("feed_issued_kg", "Feed issued (kg)", true, "0.01"), f("water_notes", "Water notes", "textarea", { full: true }), number("sick_birds", "Sick birds"), number("dead_birds", "Dead birds"), f("observations", "Daily observations", "textarea", { full: true })]} />; }

function FeedSuppliers(props) { return <ResourcePage {...props} title="Feed suppliers" endpoint="/feed/suppliers/" columns={[c("name", "Supplier"), c("phone_number", "Phone"), c("email", "Email"), c("is_active", "Active")]} fields={[f("name", "Supplier", "text", { required: true }), f("phone_number", "Phone"), f("email", "Email", "email"), choice("is_active", "Status", [[true, "Active"], [false, "Inactive"]])]} />; }
function FeedPurchases(props) { return <ResourcePage {...props} title="Feed purchases" endpoint="/feed/purchases/" createOnly columns={[c("purchase_date", "Date"), c("item", "Item #"), c("supplier", "Supplier #"), c("quantity_kg", "Quantity kg"), c("unit_cost", "Unit cost"), c("invoice_number", "Invoice")]} fields={[remote("item", "Feed item", "/inventory/items/", (x) => `${x.name} (${x.current_stock} ${x.unit})`), remote("supplier", "Supplier", "/feed/suppliers/"), number("quantity_kg", "Quantity (kg)", true, "0.01"), number("unit_cost", "Unit cost", true, "0.01"), date("purchase_date", "Purchase date"), f("invoice_number", "Supplier invoice")]} />; }
function FeedIssues(props) { return <ResourcePage {...props} title="Feed issues" endpoint="/feed/issues/" createOnly columns={[c("issue_date", "Date"), c("batch", "Batch #"), c("item", "Feed #"), c("quantity_kg", "Quantity kg"), c("notes", "Notes")]} fields={[remote("item", "Feed item", "/inventory/items/", (x) => `${x.name} (${x.current_stock} ${x.unit})`), remote("batch", "Batch", "/flocks/batches/", (x) => `${x.batch_code} — ${x.batch_name}`), number("quantity_kg", "Quantity (kg)", true, "0.01"), date("issue_date", "Issue date"), f("notes", "Notes", "textarea", { full: true })]} />; }
export function FeedPage() { return <ResourceTabs title="Feed management" description="Purchases, issues, suppliers, and consumption." tabs={[{ label: "Issues", component: FeedIssues }, { label: "Purchases", component: FeedPurchases }, { label: "Suppliers", component: FeedSuppliers }]} />; }

function EggProduction(props) { return <ResourcePage {...props} readOnly title="Production" endpoint="/eggs/production/" columns={[c("production_date", "Date"), c("batch_code", "Batch"), c("good_eggs", "Good"), c("broken_eggs", "Broken"), c("dirty_eggs", "Dirty"), c("production_percentage", "Production %", (v) => `${v}%`)]} />; }
function EggStock(props) { return <ResourcePage {...props} readOnly title="Egg inventory" endpoint="/eggs/inventory/" columns={[c("good_eggs", "Good eggs"), c("broken_eggs", "Broken"), c("dirty_eggs", "Dirty"), c("trays_available", "Trays")]} />; }
export function EggsPage() { return <ResourceTabs title="Egg production" description="Daily production performance and current egg stock." tabs={[{ label: "Production", component: EggProduction }, { label: "Inventory", component: EggStock }]} />; }

const healthBaseFields = [remote("batch", "Batch", "/flocks/batches/", (x) => `${x.batch_code} — ${x.batch_name}`)];
function Vaccinations(props) { return <ResourcePage {...props} title="Vaccinations" endpoint="/health/vaccinations/" allowDelete={false} columns={[c("scheduled_date", "Scheduled"), c("batch", "Batch #"), c("vaccine", "Vaccine #"), c("status", "Status"), c("administered_date", "Administered")]} fields={[...healthBaseFields, remote("vaccine", "Vaccine", "/inventory/items/"), date("scheduled_date", "Scheduled date"), date("administered_date", "Administered date", false), number("dose_quantity", "Dose used", false, "0.01"), choice("status", "Status", [["scheduled", "Scheduled"], ["completed", "Completed"], ["missed", "Missed"]]), f("notes", "Notes", "textarea", { full: true })]} />; }
function Medications(props) { return <ResourcePage {...props} title="Medication" endpoint="/health/medications/" createOnly columns={[c("start_date", "Started"), c("batch", "Batch #"), c("medicine", "Medicine #"), c("dosage", "Dosage"), c("quantity_used", "Used")]} fields={[...healthBaseFields, remote("medicine", "Medicine", "/inventory/items/"), date("start_date", "Start date"), date("end_date", "End date", false), f("dosage", "Dosage", "text", { required: true }), number("quantity_used", "Quantity used", false, "0.01"), f("reason", "Reason", "textarea", { required: true, full: true })]} />; }
function Diseases(props) { return <ResourcePage {...props} title="Disease records" endpoint="/health/diseases/" columns={[c("diagnosed_date", "Diagnosed"), c("batch", "Batch #"), c("disease_name", "Disease"), c("affected_birds", "Affected"), c("resolved_date", "Resolved")]} fields={[...healthBaseFields, f("disease_name", "Disease", "text", { required: true }), date("diagnosed_date", "Diagnosed date"), number("affected_birds", "Affected birds"), date("resolved_date", "Resolved date", false), f("symptoms", "Symptoms", "textarea", { full: true }), f("treatment", "Treatment", "textarea", { full: true })]} />; }
function VetVisits(props) { return <ResourcePage {...props} title="Vet visits" endpoint="/health/vet-visits/" columns={[c("visit_date", "Date"), c("veterinarian", "Veterinarian"), c("batch", "Batch #"), c("follow_up_date", "Follow-up")]} fields={[remote("batch", "Batch", "/flocks/batches/", null, false), date("visit_date", "Visit date"), f("veterinarian", "Veterinarian", "text", { required: true }), f("reason", "Reason", "textarea", { required: true, full: true }), f("findings", "Findings", "textarea", { full: true }), f("recommendations", "Recommendations", "textarea", { full: true }), date("follow_up_date", "Follow-up date", false)]} />; }
export function HealthPage() { return <ResourceTabs title="Health management" description="Vaccination, medication, disease, and veterinary history." tabs={[{ label: "Vaccinations", component: Vaccinations }, { label: "Medication", component: Medications }, { label: "Diseases", component: Diseases }, { label: "Vet visits", component: VetVisits }]} />; }

function Items(props) { return <ResourcePage {...props} title="Inventory items" endpoint="/inventory/items/" columns={[c("sku", "SKU"), c("name", "Item"), c("category", "Category"), c("current_stock", "Stock"), c("unit", "Unit"), c("is_low_stock", "Low stock")]} fields={[f("sku", "SKU", "text", { required: true }), f("name", "Item name", "text", { required: true }), choice("category", "Category", [["feed", "Feed"], ["medicine", "Medicine"], ["vaccine", "Vaccine"], ["egg_tray", "Egg tray"], ["equipment", "Equipment"]]), f("unit", "Unit", "text", { required: true }), number("reorder_level", "Reorder level", true, "0.01"), choice("is_active", "Status", [[true, "Active"], [false, "Inactive"]]), f("notes", "Notes", "textarea", { full: true })]} />; }
function StockTransactions(props) { return <ResourcePage {...props} title="Stock transactions" endpoint="/inventory/transactions/" createOnly columns={[c("transaction_date", "Date"), c("item_name", "Item"), c("transaction_type", "Type"), c("quantity", "Quantity"), c("expiry_date", "Expiry"), c("reference", "Reference")]} fields={[remote("item", "Item", "/inventory/items/", (x) => `${x.name} — ${x.current_stock} ${x.unit}`), choice("transaction_type", "Transaction", [["in", "Stock in"], ["out", "Stock out"], ["adjustment_in", "Adjustment in"], ["adjustment_out", "Adjustment out"]]), number("quantity", "Quantity", true, "0.01"), date("transaction_date", "Date"), date("expiry_date", "Expiry date", false), number("unit_cost", "Unit cost", false, "0.01"), f("reference", "Reference"), f("notes", "Notes", "textarea", { full: true })]} />; }
export function InventoryPage() { return <ResourceTabs title="Inventory" description="Current balances, expiry dates, and stock movements." tabs={[{ label: "Items", component: Items }, { label: "Transactions", component: StockTransactions }]} />; }

function Customers(props) { return <ResourcePage {...props} title="Customers" endpoint="/sales/customers/" columns={[c("name", "Customer"), c("phone_number", "Phone"), c("email", "Email"), c("is_active", "Active")]} fields={[f("name", "Customer name", "text", { required: true }), f("phone_number", "Phone"), f("email", "Email", "email"), f("address", "Address", "textarea", { full: true }), f("notes", "Notes", "textarea", { full: true })]} />; }
function Sales(props) { return <ResourcePage {...props} title="Sales" endpoint="/sales/" createOnly rowActions={(sale, reload) => <PaymentButton sale={sale} reload={reload} />} columns={[c("sale_date", "Date"), c("invoice_number", "Invoice", (v, row) => <PrintInvoice sale={row} />), c("sale_type", "Type"), c("customer_name", "Customer"), c("quantity", "Quantity"), c("total_amount", "Total"), c("payment_status", "Payment")]} fields={[date("sale_date", "Sale date"), choice("sale_type", "Sale type", [["eggs", "Eggs"], ["live_birds", "Live birds"], ["manure", "Manure"]]), remote("customer", "Customer", "/sales/customers/"), remote("batch", "Batch (live birds only)", "/flocks/batches/", null, false), number("quantity", "Quantity", true, "0.01"), f("unit", "Unit", "text", { required: true }), number("unit_price", "Unit price", true, "0.01"), number("amount_paid", "Amount paid", true, "0.01"), choice("payment_method", "Payment method", paymentMethods), f("notes", "Notes", "textarea", { full: true })]} />; }
export function SalesPage() { return <ResourceTabs title="Sales" description="Customers, payments, receipts, and invoices." tabs={[{ label: "Sales", component: Sales }, { label: "Customers", component: Customers }]} />; }

export function ExpensesPage(props) { return <ResourcePage {...props} title="Expenses" description="Farm spending and receipt evidence." endpoint="/expenses/" columns={[c("expense_date", "Date"), c("category_display", "Category"), c("description", "Description"), c("payee", "Payee"), c("amount", "Amount"), c("payment_method", "Method")]} fields={[date("expense_date", "Expense date"), choice("category", "Category", [["feed", "Feed"], ["medicine", "Medicine"], ["labour", "Labour"], ["electricity", "Electricity"], ["water", "Water"], ["repairs", "Repairs"], ["fuel", "Fuel"], ["miscellaneous", "Miscellaneous"]]), f("description", "Description", "text", { required: true, full: true }), f("payee", "Payee"), number("amount", "Amount", true, "0.01"), choice("payment_method", "Payment method", paymentMethods), f("reference", "Reference"), f("receipt", "Receipt", "file", { accept: ".pdf,.jpg,.jpeg,.png,.webp", full: true }), f("notes", "Notes", "textarea", { full: true })]} />; }
