import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("flocks", "0001_initial"), ("inventory", "0001_initial")]
    operations = [
        migrations.CreateModel(name="FeedSupplier", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("name", models.CharField(max_length=150, unique=True)), ("phone_number", models.CharField(blank=True, max_length=30)), ("email", models.EmailField(blank=True, max_length=254)), ("is_active", models.BooleanField(default=True)), ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="feed_feedsupplier_created", to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="FeedPurchase", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("quantity_kg", models.DecimalField(decimal_places=2, max_digits=12)), ("unit_cost", models.DecimalField(decimal_places=2, max_digits=12)), ("purchase_date", models.DateField(db_index=True)), ("invoice_number", models.CharField(blank=True, max_length=80)), ("item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="feed_purchases", to="inventory.inventoryitem")), ("supplier", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="purchases", to="feed.feedsupplier")), ("stock_transaction", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="feed_purchase", to="inventory.stocktransaction")), ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="feed_feedpurchase_created", to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="FeedIssue", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("quantity_kg", models.DecimalField(decimal_places=2, max_digits=12)), ("issue_date", models.DateField(db_index=True)), ("notes", models.TextField(blank=True)), ("batch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="feed_issues", to="flocks.flockbatch")), ("item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="feed_issues", to="inventory.inventoryitem")), ("stock_transaction", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="feed_issue", to="inventory.stocktransaction")), ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="feed_feedissue_created", to=settings.AUTH_USER_MODEL))]),
    ]
